### PR TITLE
Added config template for setting temporary directory path

### PR DESCRIPTION
**Pull request by robhawkes**
This adds the template for setting the temporary directory, used to place the uploaded files and store model conversion files until they are put on S3 (local files are deleted after that).

The directory path needs to end with a "/" to work with some of the legacy code from this previously being un-configurable. For example:

```
"./tmp123/"
```

A lot of this will change in v2 of Polygon City anyway with a better, more robust upload flow and model conversion system.

### CODE REVIEW

**Comment by baldur** [comment]
@robhawkes we should add a default attribute for this value ... ex: https://github.com/polygon-city/chef-buildingdb/blob/master/attributes/default.rb#L2

Also mind rebasing so the merge can go through here

**Comment by robhawkes** [comment]
Had a bit of a battle with Git for some reason but I think we're good now. I've not added a default yet, but I'll add one in and remove the conditional.

**Comment by robhawkes** [comment]
Ok, that's done now

**Comment by baldur** [comment]
hmm ... that must have been some battle ... odd that my changes that are already in master are in this diff. I'll merge but if something weird we'll solve it p)

**Pull request merged**
